---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-metrics-server-tox-py39
        - k8sapp-metrics-server-tox-flake8
        - k8sapp-metrics-server-tox-pylint
        - k8sapp-metrics-server-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-metrics-server-tox-py39
        - k8sapp-metrics-server-tox-flake8
        - k8sapp-metrics-server-tox-pylint
        - k8sapp-metrics-server-tox-metadata
    post:
      jobs:
        - stx-metrics-server-armada-app-upload-git-mirror

- job:
    name: k8sapp-metrics-server-tox-py39
    parent: tox-py39
    description: |
        Run py39 test for metrics_server
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-metrics-server/*
    vars:
        tox_extra_args: -c python3-k8sapp-metrics-server/k8sapp_metrics_server/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-metrics-server-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_metrics_server
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-metrics-server/k8sapp_metrics_server/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-metrics-server-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_metrics_server
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-metrics-server/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-metrics-server/k8sapp_metrics_server/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-metrics-server-tox-flake8
    parent: tox
    description: |
        Run flake8 for metrics-server
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-metrics-server/*
    vars:
        tox_envlist: flake8
        tox_extra_args: -c python3-k8sapp-metrics-server/k8sapp_metrics_server/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'


- job:
    name: stx-metrics-server-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/metrics-server-armada-app to
      github.com/starlingx/metrics-server-armada-app
    vars:
      git_mirror_repository: starlingx/metrics-server-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-metrics-server-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-metrics-server-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - l0pj6TPvndeBJCBKvngZrfC0vlcaRSVyoL/TcpCqFMzziXRs0+XhTBTdNq5lo+svgFjpb
          erHUVrBT6HXnmnhd43zMJpWEXCErK8YX19g9qNGfN4Ao1xQcXGLvjikgQYD+x0LaudB3q
          AIP9dv0dj74VTpmAzelEwZUcbikY+Eiss+/T69NhTkdSjBKktDXUYd9yuz8+/7SGdvsJJ
          OdgpcIDp8hqiFznQlxpAf7clIHWRo/bcUkL6ZRmE3CCw91DU/zhaTQr57e1e4f0UdNQVf
          aM9fvl+N7Z7fZtsSXu9u3XtClhEw+8Yt47wF7YE7C9NhTKloasyqdbBvaNFUyLtpBKwMS
          YCn0X1U2xn82M5SBdXYQeEz7jmJI9oVdryRY6xSi7IGkLT1o1eodI0/LNPt61t0f8SCcv
          p3Z7Aw+GCAyjLISM8SDOwpaHyBibNIbDCnI7sNcWowI9tIavuZNgYTg+4S2/6stCPpTQ7
          f63OXci46dQP0KAT6bQHNr0yXMbNjceiXfgdIuKkgiwHuAabhEhga+sKSwe5KRXURnNB0
          +sE7fYAWvnKjb2D96fm5DOf5l905kVvJ9sG4yoN3+bXk+L/WPpp+/fx+hQdQ5+bNON7BR
          qjt7KNpmzXfofQ1yrrNkjczhHRi4f5mXyem43yl3V2qhOBzQW2q5jPQEHCqEUQ=
        - c8tvWOrRrVS2viVib2wl3K35wQImXMeOEr7Y8FQqlNAE7lWtCzRZBnIX/qU64pgyDaGxC
          eyhcv7lSScB+0Gsw1Ndzdvj/FVj0K5Gwap4XkpScNUrg+T+T7eXNgGmnRk2wxP4cJzTIu
          8GDomHJobNxa0aMgbV1k5UHDVJAPGQXj+QpZE5VxVagYCxY6MschdTVudgbPVVnJvIMPc
          CGeLTCwquwlExu8Yl2MHZ8ouY2wpZTuMmIeXWHSXm0Pqu/dnmMPiGfZKvraIgHfOG4L3q
          rk5cNQyrYlLml9SCStLonngpeq6R++J4hsfY4TxMhiZQ6t48OX1OLeoUUVdqap/neYcUD
          13B4T1l0EUicUnLwKma+kAottEYcL9Cu2ppJOaDEME0pTaSAyxT5WRTh7NFHu3xIMaLpQ
          VWrjIdT6T67epIj2EgWah3JMA95X3Smjr0Vi0vLru19o9q4bLSGGUTST18sM6IEc/cof1
          UqstYJcsBgK1QGaFa7+JtCmb9LIVGdPQ2fQ0Sfvh4WGkLYxLkEYzFNoPC7V8y2mk+3hci
          NqCCQApOPoOkG4uDoiA4KkKzjfFfCPOvNbEj4Ze6SeTt8jbNk/p3YDaO/up0FEwPMooe3
          hGHkeQ/m/2Xkebn870h67fukZ7jVm3mr4bgV9WtVjn/aJZNWAW5HXkMqPm+RCg=
        - OKzaemK4Rdaqu+p1GQRWClRrpqLBxthuE9cLRNd5AXBGv4vFERat8g8QGRHikBzrxwJ/D
          XE/AyVqU6W9L0v5iW1aKLHfh6g8s3nRzRaA6nbZKX+wdxv8xeXyeV3n2cyg+/oeH1U720
          OSuXmoCklJ3TuEZnbfBkSRrU/WeaWCmb0QHa+DC+M3+YXmkKUweOrowLqpy3OS/Mj3qLT
          vQ3I4G8NkbFwK+C8/pNyfCI0nSHfj3TZMmKnaHLwyCMW0bMFUjmecq9+Ci+jJb/G3DJiv
          MnruGSsjJKeMZM8tqRB8dGyuDbLXf4hlGStXuBIhCsLMnT0svRnRIMcgJKhDUO01lGZup
          2dCaZlUV6YiAs2ClOpWaiNz0Nh0HJxBSAFnupW3HUaX/t20t1CKSFGgK3rb7cBtlkcpRo
          fN1Vn/AQenH4YmY4S9WUP4k6xfnzfzkaYJCcUoJqaecSsGMj7t8AUx13vhV9FFdFusvpr
          Hg+pGJKH0eGSH/4b+Q92r8UriWNouuniiiRCN00TM8fQKs9hBvY/JdD0SlJo14Hxwdzdt
          /U6D2EMVLAOEcUYTFTSO80GTDeEdQV7hTTpo/MDJD4KU1dt1U+vI4pGHOhHrjVoEoMkC9
          rB7vLKGue2GaZ+Pf4cs/P/YoE+0ZhQ3esw4ZUQxIAcDql2skMbqX/vKc7uFH6Y=
        - GWOmkEuKuNU/YkhvDQJyokGhmbgoDPZ46iCqPz+aX+Z2DAG/AqerkkwJ2p2XODRm2shll
          JtXIrTsPN6UilywBCitC6y7NBDzBd07IVGU/JaAiSGZ0HpyClPPsv1OVg4XpfAL7+/Lc+
          t+9iVBEaNyIyqfZCc4pnlEXk4HlmtYJk6sqEOxtWgIm7vqnDqvGfLWujDBfgTd1Vxxbqo
          NmDx8RbAIHLegFvcKc14kXCemYaEAbOYI+39TY7BdX5YC1jyCifid9sIHqXY0DhjuZNtH
          1dQCLFn0uD1JdhoKh+Eop9LI7BA0BnP8nxCRbxDjfaw62ydTrh319XT/CXr8/mVwFCSFO
          H6/7rjX8+KTLxls4OvaWVoeWK3UR9olNP9jTtfpIbnGH+uByhZFS5BWmkwUFYm5cLg3nR
          NBs/na+detN/cg4Q9vVU+1ZZ9uB+uREnKtZnqHV7pJfwM+ej6v7wYVcFXXFXwMmOzu4SW
          YOjbOsT2q7y+qf5XXby0VkmndytywHKCECc8m9jZdjjZRUS1gy5XDvBGqMN4UW1tVJKPD
          kWdstqwdbJ9Il76qIGUOG6Oe7YbcCOwqn2+0Wr6rPt+2PcqOG1tlTtQ9Wt2lTKR214PFP
          NR4uAHdjeSOE+GFghxaEOGYRGQpIjwbgQTXfrflQKegUWricGly3IepVQForEI=
        - QHik3w1egB1fnQwnZEHPBS4PB8yzbSXeHT3GyBOTsLs+ExeoBrbbb0Gw93trEIlLF6FQE
          /JXZuNkUgEMtI/kZqPv/CxIup7OxHCy6RwmYl7STAoSLwsDWjVVv44YtEyVod/snZAUuA
          lASkvydc+cNPJUwHH8JccsN2vvVyY0VhtqkxGbFF3gkA0xfGnXdhemFPifSFD5zK0WZE0
          vjimQgsKFEE/sK0XrY/WxFPTLLQXw5oVvD2l9LXdyQp23g8Osm+1gWb5t/Wu/dc0ne27O
          /hupxQE4BgtlCSoSHmfQETAm8Yvg36k8FcF52kIh1rb97slii37wCNoHUBobeyf6WFeQL
          tPpKN5hdOxlIRmbkR/8el+S1dtX3qVWFLIgAhvzfeQWs5CMRdLQVoRc/DUMyPJ+kU/ur2
          DlDE1jZw2QmDbiKzIgx1lcsSOEO6yUCZ394fvXH5n5+xO5xC+GqJWJjktgOKNGq5i8/OD
          J8sg2hEvepxsmxkjeBl5YGRgtRm8uxe2Eqdlf0pTszfgwCcoOD+smTJG1d8VXhQ2HN1WO
          IP9V9OzJ+p2HbkkrUWk0J4PAerZSMsQZM/h25jXeE77cJ0X07qiFVS4gZclqY+Ei/5OTK
          /O6ft9FlXHIjjTHlvjIEhl4r99odSsBPXsx/1kj/KCceEqo63M44/++lBVOXWU=
        - ZNjGsjs1R0k1N4qsezfg2+736cViQAWWarBkDo7xYCN2xPdSLOkW2MsBILuOG2TI1Hu0v
          BVU9ZlaDbxQJFSU56zQYDyiKVhngD3sOmuFQ3/zO3VLZcTc+PelV/jav21fhebqwbunw5
          AOvut/RghlIqQUO1hoi+TbG7K/TeVEq2zyK6fV9y6n57PKNvxMyPjniM2FZGbruZ6JbOU
          InQMdlm0+sPL3LLW7n42Opsw+Tdi5Y7iGD8HjQVUqgH7mXZclJRBWK2mMFNIWj2ZzPRLm
          4PtOs2kYDh7uU6vmwIUqa2MoiuEt0BMdVN7cbQUA25OiCv6ynYBZmHioMR5iI2dV9F+6D
          g4sjQ06hZn6c5x1qmNOaZqIaVYxEc1LHi+Opn6vynuNZdRmp8MlFRrpTyAg93GWkKInWo
          ksi52em4nSlgo/XODupn39KAUrevQscMEaQN1TEJfqD+gXbNCeKGJw/x9bUzyKyHmkTj7
          VIraSeM1IbrNm7eGe3C4u0aQpZMAyojrPO0dbAuP7QDbhZS1CZUPXmjSaLSTmNIHnJh8B
          EHMVttBZD4Zc51yaJVHQMXJle0I+9oWV/QJUp+YIZVRTXEaYDKJ3sDCjaaRkDMtMTr5En
          0Hsh+MVHe0igjxS/lDXPqkgQpv3jYVQHIFYrLuxeL+6lWX9LLKObNnUZ3CPGH8=
        - AtryfFToJeQMJSYIwURwKErFLAKNqQ24GZXyoKKgAebP7bY5QFdIMLj4mZNGHVTk36THk
          WAS4nU2aRqxsld7Y/44I0n+1GcI81cgQSkaJ7/hqF1WH3Koo9k+7x7GhAfTJqnS950oGo
          Tzqvlrx9X/uUx1RilLCBhkUTGsgzpsyDIBPgeOogKGtvImX1bpuh0cHIYkQXppvDB164w
          gX2VMy5HtiRu/AkSaE7Gd26LAg51vcDYXK/nVpH7NYWtV9rnNy2heZQvnfxnlJCENjSxc
          lo99RGl1gzr7/Ad20r9QLE37BB7pm3GV6xc+9wpQF1pcGnbQrUZeNxMUQfRAUkyej6v1a
          QxAeZg10YQkkjXLDe1Xfj52FF7mumLosmRUEE4r37JhMkdi1HtTtWHKRFhw4eZNbzIyhR
          C7baqY4DLJdvJ6YQOBXFyc9PYrwCCkxNR2fG4Lax7Yvy+XCB2y4BSo1YxBg9Ex4GazFGs
          n7z7X7afmBRqdcmDg8Mwm1IirwVlP6Wl6Gab4S+bFAIJmqWqwF43j+7C0XTpGMhqSxoJ5
          tj0EfLqK/rwfjjFRBhsFnGJYPmP6ns0nHMyu77VxObTxB1uUqd7+Ab8GatrXXZVUa4uYO
          lT0b1jpFa2TY7cQ9Q9dkGdxullJjf/46LX6jQDSXYbjVJNWF55P4T5iotF5gv8=
