{{- if .Values.sampleApp.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-server-test-app-deployment
  namespace: metric-server-test-app
spec:
  selector:
    matchLabels:
      app: metric-server-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: metric-server-test-app
    spec:
      containers:
      - name: sample-app
        image: docker.io/starlingx/stx-metrics-server-sample-app
        imagePullPolicy: IfNotPresent
        env:
        - name: TOKEN_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
      serviceAccountName: metric-server-test-app
{{- end -}}
